---
  - hosts: control
    become: true
    tasks:
      - name: install tools on control
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - curl
          - python-httplib2
